name: IngotSpleefPlus
authors:
- Budderman18
description: "A spleef plugin focused on simplicity and efficency."
main: com.budderman18.IngotSpleefPlus.Main
version: 1.2
api-version: 1.13
depend: [IngotMinigamesAPI]
softdepend: [Multiverse-Core]
commands:
    sp:
        description: Access spleef commands
        default: true
        usage: /sp [command]
        permission: ingotsp.sp
        aliases:
        - spleef
    spadmin:
        description: Access spleef's admin commands
        default: op
        usage: /spadmin [command]
        permission: ingotsp.spadmin
permissions:
    ingotsp.bypass:
        description: Allows user to ignore command blocking features
        default: op
    ingotsp.sp:
        description: Gives access to the /sp base command
        default: true
    ingotsp.sp.join:
        description: Gives access to the /sp join command
        default: true
    ingotsp.sp.randomjoin:
        description: Gives access to the /sp randomjoin command
        default: true
    ingotsp.sp.spec:
        description: Gives access to the /sp spec command
        default: true
    ingotsp.sp.leave:
        description: Gives access to the /sp leave command
        default: true
    ingotsp.sp.stats:
        description: Gives access to the /sp stats command
        default: true
    ingotsp.sp.stats.others:
        description: Gives access to the /sp stats command for other players
        default: op
    ingotsp.sp.team:
        description: Gives access to the /sp team command
        default: true
    ingotsp.sp.kit:
        description: Gives access to the /sp kit command
        default: true
    ingotsp.sp.list:
        description: Gives access to the /sp list command
        default: true
    ingotsp.sp.help:
        description: Gives access to the /sp help command
        default: true
    ingotsp.spadmin:
        descrpition: Gives access to the /spadmin base command
        default: op
    ingotsp.spadmin.arena:
        descrpition: Gives access to the /spadmin arena base command
        default: op
    ingotsp.spadmin.arena.create:
        descrpition: Gives access to the /spadmin arena create command
        default: op
    ingotsp.spadmin.arena.delete:
        descrpition: Gives access to the /spadmin arena delete command
        default: op
    ingotsp.spadmin.arena.edit:
        descrpition: Gives access to the /spadmin arena edit command
        default: op
    ingotsp.spadmin.arena.spawn:
        descrpition: Gives access to the /spadmin arena spawn base command
        default: op
    ingotsp.spadmin.arena.schematic:
        descrpition: Gives access to the /spadmin arena schematic command
        default: op
    ingotsp.spadmin.arena.regenerate:
        descrpition: Gives access to the /spadmin arena regenerate command
        default: op
    ingotsp.spadmin.arena.pos1:
        descrpition: Gives access to the /spadmin arena pos1 command
        default: op
    ingotsp.spadmin.arena.pos2:
        descrpition: Gives access to the /spadmin arena pos2 command
        default: op
    ingotsp.spadmin.arena.select:
        descrpition: Gives access to the /spadmin arena select command
        default: op
    ingotsp.spadmin.arena.toggle:
        descrpition: Gives access to the /spadmin arena toggle command
        default: op
    ingotsp.spadmin.arena.spawn.create:
        descrpition: Gives access to the /spadmin spawn create command
        default: op
    ingotsp.spadmin.arena.spawn.delete:
        descrpition: Gives access to the /spadmin spawn delete command
        default: op
    ingotsp.spadmin.arena.spawn.list:
        description: Gives access to the /spadmin spawn list command
        default: op
    ingotsp.spadmin.hologram:
        descrpition: Gives access to the /spadmin hologram base command
        default: op
    ingotsp.spadmin.hologram.create:
        descrpition: Gives access to the /spadmin hologram create command
        default: op
    ingotsp.spadmin.hologram.delete:
        descrpition: Gives access to the /spadmin hologram delete command
        default: op
    ingotsp.spadmin.hologram.refresh:
        descrpition: Gives access to the /spadmin hologram refresh command
        default: op
    ingotsp.spadmin.hologram.recalculateScore:
        descrpition: Gives access to the /spadmin hologram recalculateScore command
        default: op
    ingotsp.spadmin.help:
        description: Gives access to the /spadmin help command
        default: op
    ingotsp.spadmin.reload:
        description: Gives access to the /spadmin reload command
        default: op
    ingotsp.spadmin.version:
        description: Gives access to the /spadmin versiom command
        default: op
    ingotsp.sp.*:
        description: gives access to all /sp commands
        default: op
        children:
        - ingotsp.sp
        - ingotsp.sp.join
        - ingotsp.sp.spec
        - ingotsp.sp.kit
        - ingotsp.sp.team
        - ingotsp.sp.randomJoin
        - ingotsp.sp.leave
        - ingotsp.sp.list
        - ingotsp.sp.help
    ingotsp.spadmin.arena.spawn.*:
        description: Gives access to all /sp admin arena spawn commands
        default: op
        childern:
        - ingotsp.spadmin.arena.spawn
        - ingotsp.spadmin.arena.spawn.create
        - ingotsp.spadmin.arena.spawn.delete
        - ingotsp.spadmin.arena.spawn.list
    ingotsp.spadmin.arena.*:
        description: Gives access to all /sp admin arena commands
        default: op
        childern:
        - ingotsp.spadmin.arena
        - ingotsp.spadmin.arena.create
        - ingotsp.spadmin.arena.delete
        - ingotsp.spadmin.arena.edit
        - ingotsp.spadmin.arena.spawn.*
        - ingotsp.spadmin.arena.select
        - ingotsp.spasmin.arena.toggle
        - ingotsp.spadmin.arena.regenerate
        - ingotsp.spadmin.arena.schematic
        - ingotsp.spadmin.arena.pos1
        - ingotsp.spadmin.arena.pos2
    ingotsp.spadmin.hologram.*:
        description: Gives access to all /spadmin hologram commands
        default: op
        childern:
        - ingotsp.spadmin.hologram
        - ingotsp.spadmin.hologram.create
        - ingotsp.spadmin.hologram.delete
        - ingotsp.spadmin.hologram.refresh
        - ingotsp.spadmin.hologram.recalculateScore
    ingotsp.spadmin.*:
        description: Gives access to all /sp admin commands
        default: op
        childern:
        - ingotsp.spadmin.arena.*
        - ingotsp.spadmin.hologram.*
        - ingotsp.spadmin.help
        - ingotsp.spadmin.reload
        - ingotsp.spadmin.version
    ingotsp.arenas.*:
        description: Gives access to all arenas
        default: op